// content.js
class DescriptionGenerator {
    constructor() {
        this.isInitialized = false;
        this.chromeAvailable = false;
        this.shortDesc = null;
        this.longDesc = null;
        this.settings = this.getSettings();
        this.init();
        this.isEditPage = window.location.pathname.includes('/edit');
        this.isShowPage = !this.isEditPage && window.location.pathname.includes('/shop/products/') &&
            !window.location.pathname.includes('/new') &&
            /\/shop\/products\/\d+$/.test(window.location.pathname);
    }

    async init() {
        if (this.isInitialized) return;

        // Check Chrome API availability
        await this.checkChromeAvailability();

        // Wait for page to load
        await this.waitForPageReady();

        // Inject UI
        this.injectUI();
        this.isInitialized = true;

        // Check auto-generate
        if (this.isEditPage) {
            await this.checkAutoGenerate();
        }
    }

    async checkChromeAvailability() {
        try {
            if (typeof chrome !== 'undefined' && chrome.runtime && chrome.runtime.sendMessage) {
                this.chromeAvailable = true;
            } else {
                this.chromeAvailable = false;
            }
        } catch (error) {
            console.error('Error checking Chrome availability:', error);
            this.chromeAvailable = false;
        }
    }

    async checkAutoGenerate() {
        try {
            const settings = await this.settings;

            if (settings.autoGenerateDescriptions) {
                // Delay slightly to ensure UI is ready
                setTimeout(() => {
                    this.generateDescription();
                }, 1500);
            }
        } catch (error) {
            console.error('Error checking auto-generate setting:', error);
        }
    }

    async waitForPageReady() {
        return new Promise(resolve => {
            if (document.readyState === 'complete') {
                setTimeout(resolve, 1000);
            } else {
                window.addEventListener('load', () => {
                    setTimeout(resolve, 1000);
                });
            }
        });
    }

    async getSettings() {
        return new Promise((resolve) => {
            try {
                if (!this.chromeAvailable) {
                    const saved = localStorage.getItem('product_descripton_generator_settings');
                    resolve(saved ? JSON.parse(saved) : {
                        apiKeys: [],
                        currentApiKeyIndex: 0,
                        apiEndPoint: 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent',
                        customPrompt: ''
                    });
                    return;
                }

                const timeout = setTimeout(() => {
                    console.warn('Timeout getting settings from background, retrying...');
                    // Retry once
                    chrome.runtime.sendMessage(
                        { type: 'GET_SETTINGS' },
                        (retryResponse) => {
                            if (chrome.runtime.lastError || !retryResponse?.apiKeys) {
                                console.warn('Retry failed, using localStorage');
                                const saved = localStorage.getItem('product_descripton_generator_settings');
                                resolve(saved ? JSON.parse(saved) : {
                                    apiKeys: [],
                                    currentApiKeyIndex: 0,
                                    apiEndPoint: 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent'
                                });
                            } else {
                                resolve({
                                    apiKeys: retryResponse.apiKeys || [],
                                    currentApiKeyIndex: retryResponse.currentApiKeyIndex || 0,
                                    apiEndPoint: retryResponse.apiEndPoint || 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent',
                                    customPrompt: settings.customPrompt || ''
                                });
                            }
                        }
                    );
                }, 2000);

                chrome.runtime.sendMessage(
                    { type: 'GET_SETTINGS' },
                    (response) => {
                        clearTimeout(timeout);
                        if (chrome.runtime.lastError) {
                            console.warn('Error getting settings:', chrome.runtime.lastError.message);
                            const saved = localStorage.getItem('product_descripton_generator_settings');
                            resolve(saved ? JSON.parse(saved) : {
                                apiKeys: [],
                                currentApiKeyIndex: 0,
                                apiEndPoint: 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent'
                            });
                        } else if (!response || !response.apiKeys) {
                            // Response received but settings not properly loaded
                            console.warn('Settings response incomplete, using localStorage');
                            const saved = localStorage.getItem('product_descripton_generator_settings');
                            resolve(saved ? JSON.parse(saved) : {
                                apiKeys: [],
                                currentApiKeyIndex: 0,
                                apiEndPoint: 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent'
                            });
                        } else {
                            // Ensure all new settings have default values
                            const settings = response;

                            resolve({
                                apiKeys: settings.apiKeys || [],
                                currentApiKeyIndex: settings.currentApiKeyIndex || 0,
                                apiEndPoint: settings.apiEndPoint || 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent',
                                autoGenerateDescriptions: settings.autoGenerateDescriptions || false,
                                autoSaveProduct: settings.autoSaveProduct || false
                            });
                        }
                    }
                );
            } catch (error) {
                console.error('Error in getSettings:', error);
                const saved = localStorage.getItem('product_descripton_generator_settings');
                resolve(saved ? JSON.parse(saved) : {
                    apiKeys: [],
                    currentApiKeyIndex: 0,
                    apiEndPoint: 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent'
                });
            }
        });
    }

    injectUI() {
        if (document.getElementById('product-descripton-generator-ui')) return;

        // floating button container
        let floatingBtnContainer = document.querySelector(".floating-btn-container");
        if (!floatingBtnContainer) {
            floatingBtnContainer = document.createElement("div");
            floatingBtnContainer.classList.add("floating-btn-container");

            const floatingBtn = document.createElement("button");
            const iconImg = document.createElement("img");
            iconImg.src = chrome.runtime.getURL("src/icons/icon_48.png");
            iconImg.alt = "Product Description Generator";
            floatingBtn.appendChild(iconImg);
            floatingBtn.classList.add("floating-btn");
            floatingBtnContainer.appendChild(floatingBtn);
            document.body.appendChild(floatingBtnContainer);
        }

        const container = document.createElement('div');
        container.id = 'product-descripton-generator-ui';

        if (this.isEditPage) {
            container.innerHTML = `
            <div class="pdg-container">
                <div class="pdg-content-wrapper">
                    <div class="pdg-content" id="pdg-content">
                        <button class="pdgui-btn primary" data-action="gen-desc">
                            ✨ Generate Description
                        </button>

                        <button class="pdgui-btn primary" data-action="copy-prompt">
                            📝 Copy prompt
                        </button>

                        <button class="pdgui-btn secondary" data-action="open-options">
                            ⚙️ Settings
                        </button>
                    </div>
                    <button class="pdg-close">×</button>
                </div>
                <div class="pdg-status" id="pdg-status">Ready</div>
            </div>
        `;
        } else if (this.isShowPage) {
            container.innerHTML = `
            <div class="pdg-container">
                <div class="pdg-content-wrapper">
                    <div class="pdg-content" id="pdg-content">
                        <button class="pdgui-btn primary" data-action="copy-prompt">
                            📝 Copy prompt
                        </button>

                        <button class="pdgui-btn secondary" data-action="open-options">
                            ⚙️ Settings
                        </button>
                    </div>
                    <button class="pdg-close">×</button>
                </div>
                <div class="pdg-status" id="pdg-status">Ready</div>
            </div>
        `;
        } else {
            // Not on a supported page, don't inject UI
            return;
        }

        // Add styles
        this.injectStyles();
        document.body.appendChild(container);
        this.attachEventListeners();
    }

    injectStyles() {
        // Same styles as content_main.js
        const style = document.createElement('style');
        style.textContent = `
            #product-descripton-generator-ui {
                min-width: 250px;
                position: fixed;
                bottom: 20px;
                right: calc(50% - 175px);
                z-index: 10000;
                font-family: 'Segoe UI', Arial, sans-serif;
            }

            .pdg-container {
                background: rgb(89,69,118);
                backdrop-filter: blur(10px);
                border-radius: 12px;
                padding: 10px 15px 5px;
                min-width: 250px;
                color: white;
                box-shadow: 0 4px 20px rgba(0, 0, 0, 0.3);
                animation: slideUp 0.3s ease;
            }

            .floating-btn-container{
                position: fixed;
                bottom: 40px;
                left: 50%;
                transform: translateX(-50%);
                text-align: center;
                z-index: 9999;
            }

            .floating-btn{
                background-color: transparent;
                border: none;
                outline: none;
                cursor: pointer;
            }

            .floating-btn img {
                width: 48px;
                height: 48px;
                cursor: pointer;
                object-fit: contain;
            }

            .show{
                display: block !important;
            }

            .hide{
                display: none !important;
            }

            @keyframes slideUp {
                from { transform: translateY(100px); opacity: 0; }
                to { transform: translateY(0); opacity: 1; }
            }

            .pdg-close {
                background: red;
                border: none;
                outline:none;
                color: white;
                font-size: 24px;
                cursor: pointer;
                padding: 0;
                width: 24px;
                height: 24px;
                display: flex;
                align-items: center;
                justify-content: center;
                border-radius: 50%;
                position: absolute;
                top: -8px;
                right: -8px;
            }

            .pdg-close:hover {
                background: rgba(255, 255, 255, 0.1);
                color: black;
            }

            .pdg-content-wrapper {
                display: flex;
                align-items: center;
                justify-content: center;
            }

            .pdg-content {
                display: flex;
                align-items: center;
                justify-content: center;
                gap: 18px;
            }

            .pdgui-btn {
                padding: 5px 10px;
                border: none;
                border-radius: 8px;
                cursor: pointer;
                font-weight: 600;
                font-size: 14px;
                transition: all 0.2s;
            }

            .pdgui-btn:hover {
                transform: translateY(-2px);
                box-shadow: 0 4px 12px rgba(0, 0, 0, 0.2);
            }

            .pdgui-btn.primary {
                background: #10b981;
                color: white;
            }

            .pdg-status {
                margin-top: 10px;
                padding-top: 5px;
                border-top: 1px solid rgba(255, 255, 255, 0.1);
                font-size: 12px;
                opacity: 0.8;
                text-align: center;
            }
            
            .pdgui-btn.primary {
                background: #10b981;
                color: white;
            }
            
            .pdgui-btn.secondary {
                background: #8b5cf6;
                color: white;
            }
        `;
        document.head.appendChild(style);
    }

    attachEventListeners() {
        const container = document.getElementById('product-descripton-generator-ui');
        if (!container) {
            console.error('Container not found');
            return;
        }

        const closeButton = container.querySelector('.pdg-close');
        if (closeButton) {
            closeButton.addEventListener('click', () => {
                container.style.display = 'none';

                // Show floating button if it exists
                const floatingBtn = document.querySelector(".floating-btn");
                if (floatingBtn) {
                    floatingBtn.classList.remove('hide');
                    floatingBtn.classList.add('show');
                }
            });
        }

        // Floating button event
        const floatingBtn = document.querySelector(".floating-btn");
        if (floatingBtn) {
            // Make sure floating button is visible initially
            floatingBtn.classList.add('hide');

            floatingBtn.addEventListener('click', (e) => {
                e.preventDefault();
                container.style.display = 'block';
                floatingBtn.classList.remove('show');
                floatingBtn.classList.add('hide');
            });
        } else {
            console.warn('Floating button not found');
            // If no floating button, show the UI directly
            container.style.display = 'block';
        }

        // Action buttons
        container.querySelectorAll('.pdgui-btn').forEach(btn => {
            btn.addEventListener('click', (e) => {
                const action = e.target.dataset.action;
                this.handleAction(action);
            });
        });
    }

    async handleAction(action) {
        this.updateStatus('Processing...');

        switch (action) {
            case 'gen-desc':
                await this.generateDescription();
                break;
            case 'copy-prompt':
                await this.copyPromptWithProductName();
                break;
            case 'open-options':
                if (this.chromeAvailable) {
                    chrome.runtime.sendMessage({ type: 'OPEN_OPTIONS' });
                    this.updateStatus('Ready');
                }
                break;
            default:
                this.updateStatus('Ready');
        }
    }

    updateStatus(message) {
        const statusElement = document.getElementById('pdg-status');
        if (statusElement) {
            statusElement.textContent = message;
        }
    }

    async getPrompt() {
        const settings = await this.settings;
        
        if (settings.customPrompt && settings.customPrompt.trim()) {
            return settings.customPrompt;
        }
        alert("Please enter a custom prompt in the settings");
    }

    async copyPromptWithProductName() {
        try {
            let productName = "";
            let imageUrls = [];

            if (this.isEditPage) {
                // Get product name from form field on edit page
                const productNameElement = document.querySelector("#product_name");
                productName = productNameElement ? productNameElement.value.trim() : "";

            } else if (this.isShowPage) {
                // Extract product name from show page
                productName = this.extractProductNameFromShowPage();

                // Extract image URLs from show page
                imageUrls = this.extractImageUrlsFromShowPage();
            }

            const prompt = await this.getPrompt();

            // Create the prompt with product name and images
            let promptWithProductName = this.formatPromptWithProductInfo(prompt, productName, imageUrls);

            // Copy to clipboard
            await navigator.clipboard.writeText(promptWithProductName);

            // Update status with product name and image info
            let statusMessage = '';
            if (productName) {
                statusMessage = `Prompt copied with product: "${productName}"`;
            } else {
                statusMessage = 'Prompt copied (no product name found)';
            }

            if (imageUrls.length > 0) {
                statusMessage += ` and ${imageUrls.length} image URL(s)`;
            }

            this.updateStatus(statusMessage);

            setTimeout(() => {
                this.updateStatus('Ready');
            }, 3000);

        } catch (error) {
            console.error('Error copying prompt:', error);
            this.updateStatus('❌ Error copying prompt');
        }
    }

    extractProductNameFromShowPage() {
        let productName = "";

        // Method 1: Try to get from page title
        const pageTitle = document.querySelector('h1.subheader-title');
        if (pageTitle) {
            const titleText = pageTitle.textContent || pageTitle.innerText;
            // Remove "Product Detail" or other text to get just the product name
            productName = titleText.replace('Product Detail', '').trim();
            if (productName === '') {
                // Method 2: Try to get from breadcrumb
                const breadcrumbItems = document.querySelectorAll('.breadcrumb-item');
                if (breadcrumbItems.length >= 3) {
                    productName = breadcrumbItems[2].textContent.trim();
                }
            }
        }

        if (!productName) {
            // Method 3: Try to get from the product name field in overview
            const nameField = document.querySelector('.field_Name');
            if (nameField) {
                const text = nameField.textContent || nameField.innerText;
                const match = text.match(/Name\s*:\s*(.+)/i);
                if (match) {
                    productName = match[1].trim();
                }
            }
        }

        return productName;
    }

    extractImageUrlsFromShowPage() {
        const imageUrls = new Set(); // Use Set to avoid duplicates

        // Method 1: Look for main product images in carousel
        const carouselImages = document.querySelectorAll('.carousel-item img, .carousel-inner img');
        if (carouselImages.length > 0) {
            carouselImages.forEach(img => {
                const url = this.extractOriginalImageUrl(img);
                if (url) imageUrls.add(url);
            });
        }

        // Method 2: Look for thumbnail images
        const thumbnailImages = document.querySelectorAll('.thumbnail-item img, .img-thumbnail');
        thumbnailImages.forEach(img => {
            const url = this.extractOriginalImageUrl(img);
            if (url) imageUrls.add(url);
        });

        // Method 3: Look for any image with fancybox attribute (usually main images)
        const fancyboxImages = document.querySelectorAll('[data-fancybox] img');
        fancyboxImages.forEach(img => {
            const url = this.extractOriginalImageUrl(img);
            if (url) imageUrls.add(url);
        });

        // Convert Set to Array and limit to 5 images
        return Array.from(imageUrls).slice(0, 5);
    }

    extractOriginalImageUrl(imgElement) {
        try {
            // Get the image source from various possible attributes
            let src = imgElement.src ||
                imgElement.dataset.src ||
                imgElement.getAttribute('data-preview-url') ||
                imgElement.getAttribute('href'); // For fancybox links

            if (!src || !src.includes('cdn-p.onlinesalepoint.com')) {
                return null;
            }

            // For proxy URLs, we need to extract the original URL correctly
            // Original pattern: https://proxy.autopartify.com/unsafe/g:sm/sh:0.5/plain/https://cdn-p.onlinesalepoint.com/products/images/...
            // We need to get everything after '/plain/'

            // Check if it's a proxy URL
            if (src.includes('/unsafe/')) {
                // Find the position of '/plain/' in the URL
                const plainIndex = src.indexOf('/plain/');
                if (plainIndex !== -1) {
                    // Return everything after '/plain/'
                    return src.substring(plainIndex + 7);
                }

                // If no '/plain/' found, try to construct the original URL
                // Extract the CDN URL directly using regex
                const cdnMatch = src.match(/https:\/\/cdn-p\.onlinesalepoint\.com\/[^'"\s]+/);
                if (cdnMatch) {
                    return cdnMatch[0];
                }

                // If we can't extract cleanly, return the URL as is
                return src;
            }

            // If it's not a proxy URL, return as is
            return src;

        } catch (error) {
            console.warn('Error extracting image URL:', error);
            return null;
        }
    }

    formatPromptWithProductInfo(prompt, productName, imageUrls) {
        let formattedPrompt = prompt;

        // Add product name to the prompt
        if (productName) {
            formattedPrompt += `\n\nProduct name: ${productName}`;
        } else {
            formattedPrompt += `\n\nProduct name: [Enter Product Name Here]`;
        }

        // Add image URLs if available
        if (imageUrls.length > 0) {
            formattedPrompt += `\n\nProduct Images (${imageUrls.length}):`;
            imageUrls.forEach((url, index) => {
                formattedPrompt += `\n${index + 1}. ${url}`;
            });
        } else {
            formattedPrompt += `\n\nProduct Images: No images found`;
        }

        return formattedPrompt;
    }

    async sendMessage(message) {
        return new Promise((resolve, reject) => {
            try {
                if (!this.chromeAvailable || !chrome?.runtime?.sendMessage) {
                    reject(new Error("Chrome API not available"));
                    return;
                }

                const timeout = setTimeout(() => {
                    reject(new Error("Message timeout"));
                }, 10000);

                chrome.runtime.sendMessage(message, (response) => {
                    clearTimeout(timeout);

                    if (chrome.runtime.lastError) {
                        reject(new Error(chrome.runtime.lastError.message));
                    } else {
                        resolve(response);
                    }
                });
            } catch (error) {
                reject(error);
            }
        });
    }

    async generateDescription() {
        // Only available on edit pages
        if (!this.isEditPage) {
            this.updateStatus("Generation only available on edit page");
            alert("Please go to the edit page to generate descriptions.");
            return;
        }

        // Get form elements
        const productNameElement = document.querySelector("#product_name");
        const shortDescElement = document.querySelector("#product_short_description");
        const longDescElement = document.querySelector("#product_description");

        if (!productNameElement || !shortDescElement || !longDescElement) {
            this.updateStatus("Error: Could not find form fields");
            console.error("Form fields not found");
            return;
        }

        const productName = productNameElement.value.trim();

        if (!productName) {
            this.updateStatus("Error: Product name is empty");
            alert("Please enter a product name");
            return;
        }

        this.updateStatus("Generating descriptions...");
        shortDescElement.value = "Generating...";
        longDescElement.value = "Generating...";

        try {
            // Get settings from Chrome storage
            let response;
            try {
                response = await this.sendMessage({ type: 'GET_SETTINGS' });
            } catch (error) {
                console.error("Failed to get settings:", error);
                this.updateStatus("❌ Error: Cannot connect to extension");
                shortDescElement.value = "Error: Extension communication failed";
                return;
            }
            const { apiKeys = [], currentApiKeyIndex = 0, apiEndPoint } = response || {};

            if (!apiKeys || apiKeys.length === 0) {
                throw new Error("No API Keys configured. Please configure settings.");
            }

            const prompt = await this.getPrompt();
            const fullPrompt = `${prompt}\nProduct name: ${productName}`;

            // Try current API key, if fails due to quota, rotate to next
            let lastError = null;
            let attemptsCount = 0;
            const maxAttempts = apiKeys.length;
            let localCurrentIndex = currentApiKeyIndex;

            while (attemptsCount < maxAttempts) {
                try {
                    const currentKey = apiKeys[localCurrentIndex];

                    if (!currentKey) {
                        throw new Error("Invalid API key");
                    }

                    const apiResponse = await fetch(
                        `${apiEndPoint}?key=${currentKey}`,
                        {
                            method: "POST",
                            headers: {
                                "Content-Type": "application/json"
                            },
                            body: JSON.stringify({
                                contents: [
                                    {
                                        role: "user",
                                        parts: [{ text: fullPrompt }]
                                    }
                                ]
                            })
                        }
                    );

                    const data = await apiResponse.json();

                    // Check for quota exceeded error
                    if (data.error?.message?.includes('quota') || data.error?.message?.includes('Quota')) {
                        lastError = data.error?.message || "API quota exceeded";

                        // Try next API key
                        if (apiKeys.length > 1 && attemptsCount < maxAttempts - 1) {
                            attemptsCount++;

                            // Request rotation from background script
                            try {
                                await this.sendMessage({ type: 'ROTATE_API_KEY' });

                                // Refresh settings to get new index
                                const newSettings = await this.sendMessage({ type: 'GET_SETTINGS' });
                                localCurrentIndex = newSettings?.currentApiKeyIndex || 0;
                            } catch (error) {
                                console.warn("Failed to rotate API key:", error);
                                // Fallback to local rotation
                                localCurrentIndex = (localCurrentIndex + 1) % apiKeys.length;
                            }

                            this.updateStatus(`Quota exceeded, trying next API key...`);
                            continue;
                        }
                    }

                    if (!data.candidates?.length) {
                        throw new Error(data.error?.message || "No text generated");
                    }

                    const text = data.candidates[0].content.parts[0].text;

                    // Parse short and long descriptions from response
                    const shortMatch = text.match(/Short Description:\s*([\s\S]*?)(?:Long Description:|$)/i);
                    const longMatch = text.match(/Long Description:\s*([\s\S]*?)$/i);

                    const shortDesc = shortMatch ? shortMatch[1].trim() : "Short description not found";
                    const longDesc = longMatch ? longMatch[1].trim() : "Long description not found";

                    // Auto-fill the form fields
                    shortDescElement.value = shortDesc;
                    longDescElement.value = longDesc;

                    this.updateStatus("Descriptions generated successfully");

                    // Check if auto-save is enabled
                    const settings = await this.settings;
                    if (settings.autoSaveProduct) {
                        this.autoSaveProduct();
                    }

                    return;

                } catch (error) {
                    lastError = error;
                    attemptsCount++;

                    if (attemptsCount < maxAttempts) {
                        // Try next API key
                        try {
                            await this.sendMessage({ type: 'ROTATE_API_KEY' });

                            const newSettings = await this.sendMessage({ type: 'GET_SETTINGS' });
                            localCurrentIndex = newSettings?.currentApiKeyIndex || 0;
                        } catch (rotateError) {
                            console.warn("Failed to rotate API key:", rotateError);
                            // Fallback to local rotation
                            localCurrentIndex = (localCurrentIndex + 1) % apiKeys.length;
                        }

                        this.updateStatus(`API Error, trying next key...`);
                        continue;
                    }
                }
            }

            // All API keys failed
            throw lastError || new Error("All API keys failed");

        } catch (error) {
            console.error("Generation error:", error);
            shortDescElement.value = "Error: " + error.message;
            longDescElement.value = "";
            this.updateStatus("❌ Error: " + error.message);
        }
    }

    autoSaveProduct() {
        try {
            const saveButton = document.getElementById('js-form-btn');
            if (saveButton) {
                this.updateStatus("Auto-saving product...");
                saveButton.click();
            } else {
                console.warn('Save Product button not found');
            }
        } catch (error) {
            console.error('Error auto-saving product:', error);
        }
    }

}

// Initialize the description generator
const descriptionGenerator = new DescriptionGenerator();

// Listen for messages from popup
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
    if (request.type === 'GENERATE_DESCRIPTION') {
        descriptionGenerator.generateDescription().then(() => {
            sendResponse({ success: true });
        }).catch((error) => {
            sendResponse({ success: false, error: error.message });
        });
        return true; // Indicate that we'll send response asynchronously
    }

    // Add a new message type for show pages
    if (request.type === 'COPY_PROMPT') {
        descriptionGenerator.copyPromptWithProductName().then(() => {
            sendResponse({ success: true });
        }).catch((error) => {
            sendResponse({ success: false, error: error.message });
        });
        return true;
    }

    if (request.type === 'SETTINGS_UPDATED' && request.settings) {
        descriptionGenerator.settings = request.settings;
        localStorage.setItem('product_descripton_generator_settings', JSON.stringify(request.settings));
        sendResponse({ success: true });
        return true;
    }
});