import Settings from '../../scripts/settings.js';

// Settings UI Handler
class SettingsUI {
    constructor() {
        this.settingsManager = new Settings();
        this.init();
    }

    async init() {
        await this.settingsManager.initialize();
        this.loadCurrentSettings();
        this.attachEventListeners();
    }

    loadCurrentSettings() {
        const settings = this.settingsManager.getAll();
        document.getElementById('apiEndPoint').value = settings.apiEndPoint || '';
        document.getElementById('autoGenerateDescriptions').checked = settings.autoGenerateDescriptions || false;
        document.getElementById('autoSaveProduct').checked = settings.autoSaveProduct || false;
        this.renderApiKeyFields(settings.apiKeys || [], settings.currentApiKeyIndex || 0);
    }

    renderApiKeyFields(apiKeys, currentIndex) {
        const container = document.getElementById('apiKeysContainer');
        container.innerHTML = '';

        if (apiKeys.length === 0) {
            container.innerHTML = '<p class="no-keys-message">No API keys added yet. Click "Add API Key" to get started.</p>';
            return;
        }

        apiKeys.forEach((apiKey, index) => {
            const fieldContainer = document.createElement('div');
            fieldContainer.className = 'api-key-field-wrapper';
            if (index === currentIndex) {
                fieldContainer.classList.add('active');
            }

            const keyField = document.createElement('input');
            keyField.type = 'password';
            keyField.className = 'api-key-input';
            keyField.value = apiKey;
            keyField.disabled = true;
            keyField.placeholder = `API Key ${index + 1}`;

            const badgeLabel = document.createElement('span');
            badgeLabel.className = 'key-badge';
            badgeLabel.textContent = index === currentIndex ? 'ACTIVE' : `Key ${index + 1}`;

            const toggleShowBtn = document.createElement('button');
            toggleShowBtn.type = 'button';
            toggleShowBtn.className = 'btn-show-key';
            toggleShowBtn.textContent = 'Show';
            toggleShowBtn.addEventListener('click', (e) => {
                e.preventDefault();
                this.toggleShowKey(keyField, toggleShowBtn);
            });

            const copyBtn = document.createElement('button');
            copyBtn.type = 'button';
            copyBtn.className = 'btn-copy-key';
            copyBtn.textContent = 'Copy';
            copyBtn.addEventListener('click', (e) => {
                e.preventDefault();
                this.copyToClipboard(apiKey, copyBtn);
            });

            const deleteBtn = document.createElement('button');
            deleteBtn.type = 'button';
            deleteBtn.className = 'btn-delete-key';
            deleteBtn.textContent = 'Delete';
            deleteBtn.addEventListener('click', (e) => {
                e.preventDefault();
                this.deleteApiKey(index);
            });

            const buttonGroup = document.createElement('div');
            buttonGroup.className = 'api-key-button-group';
            buttonGroup.appendChild(toggleShowBtn);
            buttonGroup.appendChild(copyBtn);
            buttonGroup.appendChild(deleteBtn);

            fieldContainer.appendChild(badgeLabel);
            fieldContainer.appendChild(keyField);
            fieldContainer.appendChild(buttonGroup);
            container.appendChild(fieldContainer);
        });
    }

    toggleShowKey(input, button) {
        if (input.type === 'password') {
            input.type = 'text';
            button.textContent = 'Hide';
        } else {
            input.type = 'password';
            button.textContent = 'Show';
        }
    }

    copyToClipboard(text, button) {
        navigator.clipboard.writeText(text).then(() => {
            const originalText = button.textContent;
            button.textContent = 'Copied!';
            setTimeout(() => {
                button.textContent = originalText;
            }, 2000);
        }).catch(err => {
            console.error('Failed to copy:', err);
            this.showMessage('Failed to copy API key', 'error');
        });
    }

    deleteApiKey(index) {
        if (confirm(`Are you sure you want to delete API Key ${index + 1}?`)) {
            this.settingsManager.removeApiKey(index).then(() => {
                const settings = this.settingsManager.getAll();
                this.renderApiKeyFields(settings.apiKeys || [], settings.currentApiKeyIndex || 0);
                this.showMessage('API key deleted successfully', 'success');
            });
        }
    }

    attachEventListeners() {
        const form = document.getElementById('settingsForm');
        const resetBtn = document.getElementById('resetBtn');
        const addKeyBtn = document.getElementById('addKeyBtn');

        form.addEventListener('submit', (e) => this.handleSave(e));
        resetBtn.addEventListener('click', () => this.handleReset());
        addKeyBtn.addEventListener('click', (e) => {
            e.preventDefault();
            this.handleAddApiKey();
        });

        // Listen for changes in other tabs
        this.settingsManager.addListener((settings) => {
            this.loadCurrentSettings();
            this.showMessage('Settings updated in another tab', 'info');
        });
    }

    async handleAddApiKey() {
        const apiKey = prompt('Enter the API key:');
        if (!apiKey || !apiKey.trim()) {
            this.showMessage('API key cannot be empty', 'error');
            return;
        }

        const trimmedKey = apiKey.trim();
        const existingKeys = this.settingsManager.getApiKeys();

        if (existingKeys.includes(trimmedKey)) {
            this.showMessage('This API key already exists', 'error');
            return;
        }

        try {
            await this.settingsManager.addApiKey(trimmedKey);
            const settings = this.settingsManager.getAll();
            this.renderApiKeyFields(settings.apiKeys || [], settings.currentApiKeyIndex || 0);
            this.showMessage('API key added successfully', 'success');
        } catch (error) {
            this.showMessage(`Error adding API key: ${error.message}`, 'error');
        }
    }

    async handleSave(e) {
        e.preventDefault();

        const apiEndPoint = document.getElementById('apiEndPoint').value.trim();
        const autoGenerateDescriptions = document.getElementById('autoGenerateDescriptions').checked;
        const autoSaveProduct = document.getElementById('autoSaveProduct').checked;
        const apiKeys = this.settingsManager.getApiKeys();

        if (apiKeys.length === 0) {
            this.showMessage('❌ Please add at least one API Key', 'error');
            return;
        }

        const settings = {
            apiKeys: apiKeys,
            currentApiKeyIndex: this.settingsManager.getCurrentApiKeyIndex(),
            apiEndPoint: apiEndPoint || 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent',
            autoGenerateDescriptions: autoGenerateDescriptions,
            autoSaveProduct: autoSaveProduct
        };

        try {
            await this.settingsManager.saveToStorage(settings);
            this.showMessage('Settings saved successfully!', 'success');
        } catch (error) {
            this.showMessage(`❌ Error saving settings: ${error.message}`, 'error');
        }
    }

    async handleReset() {
        if (confirm('Are you sure you want to reset to default settings?')) {
            try {
                await this.settingsManager.resetToDefaults();
                this.loadCurrentSettings();
                this.showMessage('✅ Settings reset to defaults', 'success');
            } catch (error) {
                this.showMessage(`❌ Error resetting settings: ${error.message}`, 'error');
            }
        }
    }

    showMessage(message, type = 'info') {
        const messageEl = document.getElementById('statusMessage');
        messageEl.textContent = message;
        messageEl.className = `status-message show ${type}`;

        if (type !== 'error') {
            setTimeout(() => {
                messageEl.classList.remove('show');
            }, 3000);
        }
    }
}

// Initialize when DOM is ready
document.addEventListener('DOMContentLoaded', () => {
    new SettingsUI();
    console.log('Settings UI initialized');
});
